### ISSUE TITLE
Installed it, but doesn't seem to do anything. 

### ISSUE THREAD

**Issue by ericklind** [dgornjakovic/daofirst-bot#1]
Hi,
I was super excited to see this, but when I installed it on my Discord, it doesn't do anything. Doyou have any more setup instructions?

Thanks!

**Comment by danijelthales** [comment]
Just created a test discord server and added the bot. Worked perfectly. Not sure what problem u are having.

**Comment by ericklind** [comment]
Thanks for the quick response. Someone got me the link to your demo video for Barnbridge. That really helped. You might want to post that in the README.

Cheers!
